### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'to_dense'

### ISSUE THREAD

**Issue by eliscar** [lozuponelab/q2-SCNIC#13]
Hi,

I'm trying to do correlation analysis with SCNIC but I'm stacked at this point. 

qiime SCNIC calculate-correlations \
  --i-table fake_data-filtered.qza \
  --p-method sparcc \
  --o-correlation-table fake_correls.qza

I received this error: "Plugin error from SCNIC:

  'DataFrame' object has no attribute 'to_dense'

Debug info has been saved to /tmp/qiime2-q2cli-err-8mn7co9c.log"

The debug info is this: 
Correlating with sparcc
Traceback (most recent call last):
  File "/home/qiime2/miniconda/envs/qiime2-2021.4/lib/python3.8/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-891>", line 2, in calculate_correlations
  File "/home/qiime2/miniconda/envs/qiime2-2021.4/lib/python3.8/site-packages/qiime2/sdk/action.py", line 244, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/home/qiime2/miniconda/envs/qiime2-2021.4/lib/python3.8/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/qiime2/miniconda/envs/qiime2-2021.4/lib/python3.8/site-packages/q2_SCNIC/_SCNIC_methods.py", line 29, in calculate_correlations
    correls = ca.fastspar_correlation(table, verbose=True, nprocs=n_procs)
  File "/home/qiime2/miniconda/envs/qiime2-2021.4/lib/python3.8/site-packages/SCNIC/correlation_analysis.py", line 77, in fastspar_correlation
    table.to_dataframe().to_dense().to_csv(path.join(temp, 'otu_table.tsv'), sep='\t', index_label='#OTU ID')
  File "/home/qiime2/miniconda/envs/qiime2-2021.4/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_dense'

I understood that 'to_dense' is something related to pandas, so I try to install pandas but still, the error remains. 

Someone could help me fixing it? 

Thank you

**Comment by weedcentipede** [comment]
Hi, I have the exact same issue, in the same Qiime2 version (2021.4) and other env versions (2020.8 and 2020.11). 

Thanks in advance, 
Luis Alfonso.

**Comment by timyerg** [comment]
For me worked chanding pandas version:
`pip install pandas==0.25`
After the analysis change it back to newer version to avoid further issues

**Comment by sterrettJD** [comment]
This was an issue with SCNIC, resolved [here](https://github.com/lozuponelab/SCNIC/issues/19)
